### ISSUE TITLE
Projen defaults to a deprecated node version (10.17.0)

### ISSUE THREAD

**Issue by markusl** [projen/projen#1012]
See https://github.com/projen/projen/blob/3a70eda6f811e373108933ad027eb76390720dc6/src/typescript.ts#L395

This leads to mysterious build failures like

```
node_modules/@sinonjs/fake-timers/types/fake-timers-src.d.ts:11:28 - error TS2304: Cannot find name 'queueMicrotask'.

11     queueMicrotask: typeof queueMicrotask;
```

It would be best to default to an LTS version of NodeJs types (14 at the moment).

**Comment by eladb** [comment]
Yes, I guess that would be preferable. @Chriscbr what do you think

**Comment by Chriscbr** [comment]
(previous PR discussion: #926)

@eladb Hmm, yeah maybe we can first try to identify what the consequences would be / what interruption we're trying to avoid. I feel like there are two changes that we really are trying to evaluate:

Change 1: updating the default version of @types/node for TypeScript projects (mentioned in issue) to 12.x
Change 2: updating the value of minNodeVersion for projen itself to 12.x

Change 1 is the issue Markus brought up, but Change 2 is probably the bigger change that needs to happen. Change 2 will cause consumers to get errors if they try using projen with node 11 or earlier.

Related is the fact that jsii projects run on the jsii/superchain image, which will start providing node v12 by default later in September (see https://github.com/aws/jsii/pull/2946).

I _believe_ we could probably safely update the default @types/node version (doing Change 1 but not Change 2) without significant breakage since @types/node is only a dev dependency. Also, several of our own repos like constructs, cdk8s-core, and construct-hub all have minNodeVersion explicitly set, so they won't be affected by the change.

I could probably derisk these changes by manually upgrading a couple other repos to @types/node v12 and/or minNodeVersion v12 and checking if anything breaks.

**Comment by markusl** [comment]
@Chriscbr what would be the case for supporting NodeJs prior to 12.x? 16.x is becoming LTS in a month (see https://nodejs.org/en/about/releases/) so I think the _default_ version should likely be 14 instead of 12, with the option of using 12 until the end of the maintenance period (May 2022).

**Comment by Chriscbr** [comment]
I don't think there's any specific needs to support older NodeJs version - I think we're just trying to minimize the number of downstream repos we need to make manual changes to (but at some level it might be unavoidable).

Also note to self - when we are are upgrading the default Node version, we can also change the default tsconfig.json "lib" value from es2018 to es2019, since all of es2019 is supported by Node 12 and above according to https://node.green/.
