### ISSUE TITLE
Explicit toolchain dependency (or stop using jsii/superchain)

### ISSUE THREAD

**Issue by eladb** [projen/projen#1065]
Currently, all JSII projects use a "kitchen sink" container image called `jsii/superchain` which bundles all the tools needed to build & package JSII projects. This is a pragmatic solution, but it's not optimal. It means, for example, that users don't have much control over their build environment and that builds & releases are quite slow since they have to pull this huge image on every run.

Projen should offer a fine-grained model for toolchain dependencies and have the various workflows synthesize based on this model. This will also allow us to offer developer-side support for tool installations (via tools like homebrew for example).

Abstractly, project types should be able to declare their toolchain dependencies via the Dependencies API. Probably via some special type of dependencies (or repurpose one of the existing types).

Then, we need some kind of a provider pattern that will allow mapping toolchain dependency to a provider-specific definition. For example, GitHub workflows will use one of the `actions/setup-xxx` actions to install tools in workflows based on the project model. We will be able to then offer a local provider that will check that a certain tool is installed locally and even control it via tools like `nvm` or `rvm`, etc.

**Comment by eladb** [comment]
@RomainMuller @Chriscbr @iliapolo curious what y'all think about this.

**Comment by mmcculloh-dms** [comment]
Sounds like this can go towards [this issue](https://github.com/projen/projen/issues/956) as well. I think having a new dependency type for this sort of thing would be super useful.

**Comment by Chriscbr** [comment]
> releases are quite slow since they have to pull this huge image on every run

Just to put a number on this - from what I'm seeing, it takes about 50-70 seconds to pull the jsii/superchain at the beginning of every GitHub workflow run. (Q: will be longer/shorter with the newer superchain images?) Meanwhile running `actions/setup-xxx` actions typically take a few seconds each from what I've seen.

Part of me wonders if running on container images is the correct solution in the long run, since they're supposed to be this universal-ish tool for defining build/runtime environments. At some point once you have enough dependencies, saving them as an image should (in theory) save you some time. But this assumes you have already have the image built and downloaded...

I feel like any long term solution should probably support both kinds of strategies:

- "I'm providing an image with all of the toolchain dependencies"
- "I want the toolchain dependencies to all be set up by projen in the CI/CD provider I choose"

**Comment by eladb** [comment]
Keep

**Comment by mrgrain** [comment]
There is also a huge issue with running Docker in Docker on GitHub action and sharing files on the file system.
I had a to write a nasty workaround: https://github.com/mrgrain/streamlink-serverless/blob/main/projenrc/WorkflowDockerPatch.ts

Also related #2094
