### ISSUE TITLE
The version is always 0.0.0 in package.json

### ISSUE THREAD

**Issue by wchaws** [projen/projen#1141]
The `version` field in `package.json` is always 0.0.0

```
  "main": "lib/index.js",
  "license": "Apache-2.0",
  "version": "0.0.0",
  "jest": {
  ```

**Comment by Chriscbr** [comment]
This is a (currently) expected behavior of projen, where the package version is saved as 0.0.0, and it only gets modified during releases as part of the `Release` component.

I'm curious how you discovered this (e.g. were you trying to change the file manually, or through one of the methods on `NodeProject`?) I'm curious what other ways/places we can surface this automatic behavior to the user (at least, when they are trying to override it).

**Comment by willdady** [comment]
> This is a (currently) expected behavior of projen, where the package version is saved as 0.0.0

@Chriscbr Running `yarn bump` updates the version in package.json? If I then run `yarn build` it seems to _undo_ the change to package.json?

I'm confused by what exactly the purpose of `yarn bump` is and how it relates to `yarn release` and what is the workflow for generating a release when NOT using GitHub actions.

**Comment by Chriscbr** [comment]
> what exactly the purpose of `yarn bump` is and how it relates to `yarn release`

`yarn release` dispatches to `yarn bump` to update `package.json` and generate a changelog file. It then runs `yarn build` with the "RELEASE" flag to generate the publishable artifacts. (The "RELEASE" flag will prevent `version` in `package.json` from being changed).

> what is the workflow for generating a release when NOT using GitHub actions

I don't believe the release command does anything GitHub-action specific. There is a brief note about manual releases at the end of https://github.com/projen/projen/blob/main/docs/releases.md#release-triggers - but in a nutshell, once you have run `yarn release` in your directory so that publishable artifacts (maven jar, npm tarball, ...) are within `dist/`, you can run `publish:git` to update your changelog and create a release commit, and run `publish:npm` or `publish:maven` etc. to upload the language-specific artifacts to the appropriate place.

This workflow is confusing, I'll admit. Ideally users should not have to know all of the details of how `yarn release` works. I wonder:

- Would it help if the "bump"/"unbump" tasks were hidden as an implementation detail?
- What if "publish" wasn't a step in the "build" task, but just invoked within the "release" task? The fact that the build task _implicitly_ creates the packaging artifacts is slightly unintuitive to me, but that could just be me. Are there failure modes where a `build` can succeed but the `packaging` fails (and if so, are there ways we could catch these in jsii instead)?

And besides trying to simplify the API, update the documentation on what each of these tasks do / what the inputs/outputs are besides the one-line descriptions might be helpful.

@eladb (resident expert on releasing/publishing) WDYT?

**Comment by wchaws** [comment]
> This is a (currently) expected behavior of projen, where the package version is saved as 0.0.0, and it only gets modified during releases as part of the `Release` component.
> 
> I'm curious how you discovered this (e.g. were you trying to change the file manually, or through one of the methods on `NodeProject`?) I'm curious what other ways/places we can surface this automatic behavior to the user (at least, when they are trying to override it).

Actually, I was trying to fetch pre-built binary based on package.json's version.

**Comment by gradybarrett** [comment]
@Chriscbr `publish:git` is now part of a manual `release`:

```json
"release": {
      "name": "release",
      "description": "Prepare a release from \"main\" branch",
      "env": {
        "RELEASE": "true"
      },
      "steps": [
        {
          "exec": "rm -fr dist"
        },
        {
          "spawn": "bump"
        },
        {
          "spawn": "build"
        },
        {
          "spawn": "unbump"
        },
        {
          "spawn": "publish:git"
        },
        {
          "exec": "git diff --ignore-space-at-eol --exit-code"
        }
      ]
    },
```

So the workflow is just `yarn build && yarn release`.

It sounds like maybe there's still confusion about how projen is doing version management. It's natural to expect a usable version value in your package.json if you're used to managing the version that way. But with projen, or any other project using a standard-version-like library that may not be the case.

#1267 looks like the concrete use case that keeps the above simple workflow but allows folks to customize manual releases in the way they need to.

But I do wonder if there's a way to keep the package.json version in sync with the latest tag to keep this question from popping up over and over. 🤔

**Comment by Dipankar2310** [comment]
Same issue, when I try to build the artifacts, they are always generated for 0.0.0 version, what is the way to get artifacts for specified version
