### ISSUE TITLE
Unable to extract the values using cdk synth command for Fn.importValue

### ISSUE THREAD

**Issue by aritranagnordcloud** [projen/projen#1220]
Hi Team,

I have an implementation where i need to fetch the existing ECS Cluster details. I have the import values from the VPC and Security Group of another base stack. However, While using the Fn.importValue i am getting an error : 

> All arguments to look up a security group must be concrete (no Tokens)

Here is my source code 
`    ecs.Cluster.fromClusterAttributes(this, 'existing', {
      clusterName: Fn.importValue(`${propsBackend.clusterName}-ExistingClusterStackName`),
      vpc: vpc,
      securityGroups: [
        ec2.SecurityGroup.fromLookup(
          this,
          'ECSInstanceSecurityGroup',
          Fn.importValue(`${propsBackend.clusterName}-ExistingClusterSecurityGroup`),
        ),
      ],
    });`

Whenever i run the cdk synth or cdk deploy command : 
i am getting the above error 
**Error: All arguments to look up a security group must be concrete (no Tokens)**

Please suggest what needs to be done here.

**Comment by Chriscbr** [comment]
Hi @aritranagnordcloud. From the details you've provided, I believe your problem is unrelated to projen, so I'm closing this issue. You're welcome to open an issue instead on the [AWS CDK](https://github.com/aws/aws-cdk) repository, or find help through one of the [community resources](https://github.com/aws/aws-cdk#getting-help).
