### ISSUE TITLE
TypescriptProject tsconfig.include default is incorrect

### ISSUE THREAD

**Issue by kaizen3031593** [projen/projen#1309]
I'm trying to build a projen `TypescriptProject` and came across this default discrepancy.

The default for `tsconfig` is "default options", which means that the default for `tsconfig.include` is "all `.ts` files recursively", which should be `['**/*.ts']`. 

However this is not the case; when I build my project I find that `tsconfig.include = ['src/**/*.ts']`. This means that the files in the `test` and `bin` folder do not compile to javascript, causing some consternation on my part.

https://github.com/projen/projen/blob/898dd97daf02b47166215ac87294f9405c2eebdd/src/typescript/typescript.ts#L242-L244

This was introduced in this commit: https://github.com/projen/projen/commit/fef3de3f004831ad8a06a39fc38c55dcd9c61725.

I propose that we honor the documented default of all `.ts` files. I'll submit a PR momentarily.

**Comment by kaizen3031593** [comment]
When adding `**/*.ts` to the `include` option I get an error saying that the `rootDir` (default to `src`) is expected to contain all source files and all files in the `test` folder are not in `rootDir`.

So I see why `${this.srcdir}/**/*.ts` was added. I also read the key to all this under the docstring for `testdir`:

https://github.com/projen/projen/blob/898dd97daf02b47166215ac87294f9405c2eebdd/src/typescript/typescript.ts#L28-L35

That leaves just my code in `bin` not compiling, but I will simply move it to `src` and have it live there.

Leaving this issue up for now because I feel like the documentation could be improved, specifically that `tsconfig.include` should not have a misleading default message!

**Comment by Chriscbr** [comment]
Thanks for calling this out Kaizen. 🙏

The default behavior we have in `TypeScript` project is specify a `rootDir` and `outDir` in tsconfig so that TypeScript source files and JavaScript output files are stored in separate directories (with mirrored directory structures) - this is different from how typescript is compiled in the AWS CDK if I understand correctly. So if you want to have typescript files in "bin" and "test" directories, the question under this model would be, where should the output go?

We should definitely add documentation around this, since it's pretty relevant for folks trying to move existing projects into projen. There's more than one way to shear a sheep when it comes to TypeScript compilation, and even a tiny bit of explanation could go a long way.

(I also wonder whether it makes sense for this opinionated behavior to be the default behavior at the `TypeScriptProject` level. If the default or most common option used by other TypeScript projects is to output JavaScript adjacent to the TypeScript files, maybe that should really be the default. Or perhaps the user should be required to choose between these "compilation strategies" - i.e. no implicit default).

Thoughts?

**Comment by kaizen3031593** [comment]
I've had a night to sleep on this and I think that my main misunderstanding with projen is the opinionated defaults. Defaulting `rootDir` and `outDir` to `src` and `lib` respectively differs from the expected default of both (defined [here](https://www.typescriptlang.org/tsconfig#rootDir) and [here](https://www.typescriptlang.org/tsconfig#outDir)).

I see this as a fundamental difference between CDK defaults and projen defaults.

I wonder if there is a way to support both defaults (by both i mean ALL opinionated and ALL expected defaults) hidden behind a flag or something. If I'm creating a new `projen` project I'm happy to follow these opinionated defaults, but when I'm migrating a project to `projen` these defaults do get in the way.

Maybe something like:
```ts
const project = new typescript.TypeScriptProject({
  defaults: typescript.Defaults.EXPECTED // or typescript.Defaults.PROJEN-MANAGED
  ...
});
```

Just a thought. Seems like an easy way to support multiple project set-up defaults as well as the option to support more in the future.

**Comment by Chriscbr** [comment]
Related: https://github.com/projen/projen/issues/183
