### ISSUE TITLE
Overriding dependency specs

### ISSUE THREAD

**Issue by MrArnoldPalmer** [projen/projen#1342]
When using the `ReactTypeScriptProject` in cdklabs/construct-hub-webapp, I was experimenting with moving all of our dependencies to `devDependencies`, because none of them are actually used at runtime for this package. The artifacts shipped in npm are just a bunch of static webapp assets to be copied wherever they are useful.

However, it appears that the `ReactTypeScriptProject` adds `react`, `react-dom`, `react-scripts`, and `web-vitals` to `dependencies` within `package.json`. I believe this is because `create-react-app` puts these there by default. However, I would like to override this and move them all to `devDependencies`. I'm able to add these to `devDeps`, but I can't remove them from `deps`. I tried mutating properties directly IE `package.devs = [];`, but this doesn't work as that property is not an array like the inputs of the constructor.

Seems like there should be escape hatches for arbitrarily changing properties in `package.json`? @Chriscbr @eladb what do you think?

**Comment by mbonig** [comment]
I believe this is also an issue if you want to set the react version yourself through the deps:

```
  deps: ['react@16'],
```

This also fails because of this line:

https://github.com/projen/projen/blob/main/src/dependencies.ts#L143

How can clients of the project class override (or otherwise have finer control) the dependencies that come pre-packed with the projen class?

**Comment by eladb** [comment]
@MrArnoldPalmer first off, I think you are right that all of these deps should just be dev-deps by default. Let's change that!

And yes, since package.json dependencies have special handling (because there's a bit of magic there that allows you not to specify versions), using standard escape hatches doesn't really work for them.

I think @mbonig's direction to simply relax the constraint that blocks users from modifying a dependency is where we should end up, so you'll basically be able to imperatively update any deps created by the project.

In your case, you should be able to remove the existing deps from `dependencies` using `project.deps.removeDependency()` and then add them using `project.addDevDeps()`.

I'll look into this.
