### ISSUE TITLE
Add documentation about how to edit and customize GitHub workflows

### ISSUE THREAD

**Issue by xhiroga** [projen/projen#1592]
I want to configure the GitHub workflow, especially `.github/workflows/upgrade-main.yaml` to change cron expression, in a CDK project.

However, the file is set as read-only. I guess the correct way to configure it is using the projen.

How can I configure workflows through the projen?

What I did:

- See source code of `AwsCdkConstructLibrary`
- See the index of [docs](https://github.com/projen/projen/tree/main/docs).

**Comment by Chriscbr** [comment]
I think this can be split into two issues:

> How can I configure workflows through the projen?

It looks like we don't have docs about this (this actually surprises me!). It will probably take me a bit longer to write up that explanation, but in the interim I can recommend you check out the [API reference](https://projen.io/api/API.html) and look at the docs for `GitHub`, `GitHubWorkflow`, and `Job`. For an example of how these can be used together to add workflows, you can look at this snippet of source code: https://github.com/projen/projen/blob/65b4194c163f47ba4842981b0c92dbe516be787b/src/github/auto-approve.ts#L67-L105

It also should be possible to make overrides in most files including workflows through escape hatches - see https://github.com/projen/projen/blob/main/docs/escape-hatches.md for more info.

> I want to configure the GitHub workflow, especially .github/workflows/upgrade-main.yaml to change cron expression

It turns out this workflow file is generated by the `UpgradeDependencies` component, and the cron expression can be customized like this:

```ts
new Project({
  // ... other options
  depsUpgradeOptions: {
    workflowOptions: {
      schedule: javascript.UpgradeDependenciesSchedule.expressions(["0 0 * * 1-5"]),
    },
  },
})
```

**Comment by jkodroff** [comment]
@Chriscbr As a (hopefully) quick improvement, would it be possible to add a link to GitHub Actions on the main website page? I was also having a difficult time finding GH examples, but am grateful to have found them here!

**Comment by Chriscbr** [comment]
I've created a small PR: #1597 feel free to suggest other links to add if you had something else in mind 🙂

**Comment by rantoniuk** [comment]
3 years later I still ended up here to find out how to customise that update-main cron query ;-)
How about adding this example to https://projen.io/docs/api/awscdk#buildworkflowoptionsoptional- ?

**Comment by mrgrain** [comment]
> 3 years later I still ended up here to find out how to customise that update-main cron query ;-) How about adding this example to https://projen.io/docs/api/awscdk#buildworkflowoptionsoptional- ?

Contributions are welcome!

**Comment by rantoniuk** [comment]
@mrgrain I took a quick peek around the docs and after a while I realised that the main problem is different. 

The documentation of the `schedule` actually [exists here](https://projen.io/docs/api/javascript?_highlight=upgradedependenciesoptions#projen.javascript.UpgradeDependenciesWorkflowOptions.property.schedule) and while it's missing the default value (that I will add), the main problem is that when looking at [AwsCdkConstructLibraryOptions.property.depsUpgradeOptions](https://projen.io/docs/api/awscdk/#projen.awscdk.AwsCdkConstructLibraryOptions.property.depsUpgradeOptions) the type `UpgradeDependenciesOptions` is not hyperlinked in the property section nor in the table listing the properties. 

This applies to most (but not all) of the TS types, see for example [AwsCdkConstructLibraryOptions](https://projen.io/docs/api/awscdk/#awscdkconstructlibraryoptions-), all of the property types are not hyperlinked EXCEPT suddenly one at the end [LambdaFunctionCommonOptions](https://projen.io/docs/api/awscdk/#projen.awscdk.LambdaFunctionCommonOptions).

Now, I'm guessing this is coming out of a generator? Do you think it is easily fixable to detect the TS types and hyperlink them easily everywhere? 

Point me to anything I can contribute via my PR that will add the schedule default value, happy to help.
