### ISSUE TITLE
Disabling `depsUpgrade` turns off related tasks

### ISSUE THREAD

**Issue by moltar** [projen/projen#1601]
When disabling `depsUpgrade` options the `projen upgrade` task is nuked as well.

However, the docs state:

> Use github workflows to handle dependency upgrades.

I totally assumed it will just remove the GH workflow, but keep the tasks for my manual local use.

**Comment by cgatt** [comment]
I'm looking at ways to address this issue, however the current behaviour is a bit tangled due to the mutually exclusive options between `dependabot` and `depsUpgrade`. Will look into it further and raise a PR for a breaking change that moves dependabot setup for Node projects under the UpgradeDependencies class for consistency (As it is a form of dependency upgrade management and should be parallel to the workflow approach) and provides a more intuitive options interface to allow setup of local task, github workflow or dependabot independently.

In the meantime, the workflow can be disabled without removing the local task by including the following in your project config:
```ts
{
  depsUpgrade: true,
  depsUpgradeOptions: {
    workflow: false,
  },
}
```

**Comment by moltar** [comment]
Thanks, Chris!

A bit off-topic, but don't know where the topic is:

> Will look into it further and raise a PR for a breaking change that moves dependabot setup for Node projects under the UpgradeDependencies class for consistency

Would be great if we could have a pluggable dependency update strategy. E.g. I use Renovate for deps, and currently, there is no support for it in projen. But I think it can be added because Renovate has an open-source solution, [that can run via GitHub Action as well](https://github.com/renovatebot/github-action).
