### ISSUE TITLE
Rearchitect projen to use constructs framework

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#1763]
Components in projen (such as `NodePackage`, `Eslint`, `JsonFile`, etc.) should extend `Construct` from the [constructs framework](https://github.com/aws/constructs) instead of extending our own custom `Component` type.

Motivations:

1. ~It should be possible for users to not only share/reuse project types, but also share and reuse individual projen components/constructs. I think the reason people don't do this right now is because it's not possible, but I'm not sure (this needs to be validated).~ (Currently this is possible without constructs, so I don't think this is deciding factor)
2. Allow for introspection into the "project tree". Currently all components are added directly to the `Project` class, so the components are not created into a tree. I think modeling components as a tree will make it easier for users to figure out how components or files are being generated since we can generate the "tree" as an artifact (like the `tree.json` generated by AWS CDK), and expose it for assorted purposes. This could enable features like e.g. a command `projen inspect file.txt` which could automatically determine which projen component generated a particular file.
3. Standardize constructor syntax for components. Right now different components take different kinds of lists of arguments when you construct them. Most of them take some kind of `Project` as their first argument, and some `options` object as their second argument, but not all of them. Standardizing this makes it easier to learn and use the framework, makes it easier to do code generation for, etc.
4. Open up future interoperability between "projen" components and other CDKs like cdktf, AWS CDK, etc.

`constructs` is fairly unopinionated and it doesn't bind projen to other technical decisions, such as whether or not the framework should use [jsii](https://github.com/aws/jsii/) for multi-language support or not etc.

Implementation POC here: https://github.com/projen/projen/pull/1671

**Comment by moltar** [comment]
I am also in favour of this! I think this would add some stability and also allows for a more clear path to expansion. Coming from CDK, and knowing that the projen is also a big part of the community, initially, I totally assumed it was using constructs too, as it felt like a similar design. But when I peeked under the hood, I was surprised to see that it was _not_ using the constructs framework. I think because of that things feel a bit messy. I miss the Aspects (CDK-only concept now, but was part of constructs before) and many other conveniences that constructs afforded.

IMO we are not seeing a big community uptake in third-party components/project types partially because of this. There is no clear path for implementing a component package.
