### ISSUE TITLE
Overrides are not reflected in deps.json causing renovate trying to update those

### ISSUE THREAD

**Issue by Hi-Fi** [projen/projen#2126]
Currently there's 3 overrides in our constructs: 
```json
  "overrides": {
    "@types/responselike": "1.0.0",
    "got": "12.3.1",
    "@types/prettier": "2.6.0"
  },
```
When renovate runs, it tries to offer updated for those, which causes failure as `projen` run would revert versions (and we check in pipeline that code is not mutated).

`upgrade` task seems to be ignoring overrides, but Renovate doesn't. 

Not sure which one works incorrectly, as at least in Renovate support to overrides was explicitly added: https://github.com/renovatebot/renovate/issues/15278.

# Expected result

Renovate should ignore overrides, or at least offer flag to ignore those.

As versions are not in `.projen/deps.json`, some additional logic is needed.

**Comment by mrgrain** [comment]
## Preamble 

These package resolutions are fixes for temporary problems. We should check if we can remove them again.

---

ℹ️ **I have no expierence with Renovate, but assume it's something like Dependabot. Pleas correct my understanding if this is wrong.**

> `upgrade` task seems to be ignoring overrides, but Renovate doesn't.
That's correct and my understanding how overrides/package resolutions ought to work. It's an explicit instruction to the package manager how to resolve versions for (transitive) dependencies. These resolutions are usually in place because something doesn't work otherwise. Upgrading them would defeat it's purpose.

> Renovate should ignore overrides, or at least offer flag to ignore those.
I agree. Did you mean to open this issue with Renovate?

> As versions are not in `.projen/deps.json`, some additional logic is needed.
`deps.json` does only track direct dependencies not transative dependencies. And overrides/resolutions are instructions for a package manager. I don't see what benefit adding resolutions would bring.

--- 

I assume you need to fix this somehow. Here are your options:
- Don't use renovate. projen offers smililar functionalilty via the `upgrade` task
- Update the resolutions to the latest versions in your project
- Remove the resolutions completey from your project

For the last two options, see [Escape Hatches](https://projen.io/escape-hatches.html).

**Comment by Hi-Fi** [comment]
Those overrides are on normal CDK construct, so something that's not explicitly added. Those are also internal, so CIs are not on GitHub that would be easy option for Projen project. That's also one reason why Renovate is in use. Other is that same mechanism for dependency maintenance is used on applications and constructs.

Renovate is quite similar to dependabot, but offers some nice additions to it like grouping of dependencies to same PR.

Handling of those overrides was added to Renovate last May, so I doubt that handling of those is not going to be removed. 

So for the options I don't see any of those work, and actually started to check the projen code how those overrides could be got to renovate's ignore list like now packages with defined versions (by projen) are.

**Comment by mrgrain** [comment]
> Those overrides are on normal CDK construct, so something that's not explicitly added. 

Yes, they are not explicitly added by you, but by projen to avoid broken upstream dependencies. They come with the `JsiiProject` type and like other dependencies are explicitly required for the project type to work.

> So for the options I don't see any of those work, and actually started to check the projen code how those overrides could be got to renovate's ignore list like now packages with defined versions (by projen) are.

So does Renovate support projen by default, or is that something you've added to your config? 

--- 

Package resolutions are addedd to `package.json`, with the exact key depending on the used package manager. It should be possible parse that file.

**Comment by mrgrain** [comment]
My bad @Hi-Fi I wasn't aware Renovate Bot is supported in projen 🤯  

Thanks for finding this and for working on the PR!
