### ISSUE TITLE
[Windows] Unable to use cdk command with projen

### ISSUE THREAD

**Issue by DarthHaider** [projen/projen#2144]
Describe the bug
Unable to run any cdk command on Windows OS after the project is initialized.

To Reproduce
npx cdk --app lib/integ.default.js diff

The following error occurs:

'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Subprocess exited with error 1

Expected behavior:
Executing "npx cdk --app lib/integ.default.js diff" should have compiled integ.default.ts to integ.default.j

Version:

OS: Windows 10
Programming Language: Typescript
CDK Version: 2.44
Projen Version: 0.63.5
Node Version: v18.2.0
Git version: 2.35.1.windows.2
pipenv version:  2022.9.24
npm version: 8.9.0

**Comment by mrgrain** [comment]
Thanks for reporting this @DarthHaider 

Can you confirm the command you run to setup the project?

Saying that, Projen doesn't really have anything to do with what happens when you run `npx cdk`. It does sound like one of the numerous issues with (Windows) path names containing spaces.

What are your versions of node?
Where is node installed? (You might use `where node` for this)
What's the path of your project?

**Comment by alimhabib** [comment]
I have the same issue,
