### ISSUE TITLE
Feature request: Support for local npm packages

### ISSUE THREAD

**Issue by mvs5465** [projen/projen#2420]
We are developing a node package and using this package as a dependency in other repositories. It would be nice if there was a way to reference this package locally instead of having to upload it to a package store.

In npm you can either do an npm link or directly npm install:
```
cd ../my-library
npm link
cd ../my-original-repo
npm link @namespace/my-library
```
or
```
npm install ../my-library
```

Neither of these options appear to be currently supported by projen. This is particularly difficult because running `npx projen build` will overwrite any changes you make to the package.json, essentially making it impossible to both use projen and a local package.

**Comment by mvs5465** [comment]
Thanks @mrgrain that works perfectly! Appreciate the fast response.

Do you think there would be any way to use a projen task to set this property dynamically?

**Comment by mrgrain** [comment]
> Do you think there would be any way to use a projen task to set this property dynamically?

I'm not sure I quite understand what your goal is. Could you elaborate how you would envision something like this and what problem it is solving?

---

Generally speaking, dependencies are intended to be owned by `projen` and defined as code.
But I guess since it all is code one could introduce a projen task that updates the code that defines dependency based on some rules. Or maybe more realistically it would introduce a `dependencies.json` file that your `projen` project could read and turn into dependencies... But I guess you see where I am going with this.

If your intention is really about having a monorepo, there are solutions available that implement monorepo support (e.g. [nx-monorepo](https://aws.github.io/aws-prototyping-sdk/typescript/nx-monorepo/index.html)).
The built-in support is unfortunately very basic.

**Comment by mvs5465** [comment]
Gotcha yeah that makes sense. My main goal here is to make it so our developers can switch between using a local copy of the package stored at `../my-library` and a remote version stored as `@namespace/my-library`. 

Thinking something like this would be nice, but I know the exec expects shell commands:

```
project.addTask('use-local', {
  description: 'Use local package',
  exec: projen.addDeps("@namespace/my-library@file:../my-library"),
});

project.addTask('use-remote', {
  description: 'Use remote package',
  exec: projen.addDeps("@namespace/my-library@1.2.3"),
});
```

**Comment by mvs5465** [comment]
This might be easy enough:
```
const useLocal = false; // set this to true if you want to develop using local
if (useLocal) {
  project.addDeps('@namespace/my-library@file:../my-library');
} else {
  project.addDeps('@namespace/my-library@1.2.3');
}
```

**Comment by mrgrain** [comment]
Gotcha, I understand what you mean now. Feels related to #2399

Effectively we want an easy way to overwrite the dependency definitions when we run `projen` in local dev mode (however we detect this). But of course in CI/CD this should use the production-like dependencies. And we also can't have devs (or CI/CD for that matter) worry about synthesizing the right thing.

**Comment by mrgrain** [comment]
> This might be easy enough:

It's a starting point. You could even detect it based on a en environment variable (or absence thereof).
The tricky bit is that both branches of the condition will yield different output to files like `package.json`

**Comment by mrgrain** [comment]
If `npm link` works for you, it might be possible to automated this as a postSynthesize command.

Something like (but honestly no idea if that would work):
```ts
class MyProject extends BaseProjectClass {
  public postSynthesize() {
    if (!process.env.CI) {
      const localPackages = ['my-library'];
      localPackages.forEach(pkg => {
        child_process.spawn(`cd ${pkg} && npm link && cd ../${this.dir} && npm link ${pkg}`)
      }
    }
  }
}
```

**Comment by mvs5465** [comment]
Interesting suggestion! I think we have a path forward now, thanks for the assistance!
