### ISSUE TITLE
Bump precondition fails on windows

### ISSUE THREAD

**Issue by alimhabib** [projen/projen#2427]
Hello All I am building projen and try to test on windows ( my dev machine) but no commands ever work for example 

`yarn build` will gives error 

```
Task "build » package" failed when executing "if [ ! -z ${CI} ]; then rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist; else np
x projen package-all; fi" (cwd: C:\Repository\cdk-infra\aws-monitor-alarms-library)
error Command failed with exit code 1.
```
`npm run bump ` will gives error 

```
� bump | condition: ! git log --oneline -1 | grep -q "chore(release):"
'!' is not recognized as an internal or external command,
operable program or batch file.
� bump | condition exited with non-zero - skipping
```

my projen,js looks like 

```
const { awscdk } = require('projen');
const project = new awscdk.AwsCdkConstructLibrary({
  author: 'xxxxx',
  authorAddress: 'xxxxxxxxxxx',
  cdkVersion: '2.1.0',
  peerDependencies: [
    'aws-cdk-lib',
  ],

  devDeps: [
    'aws-sdk',
  ],
  defaultReleaseBranch: 'master',
  name: 'xxxxxxxxxxxxxxxxx',
  repositoryUrl: 'xxxxxxxxxxxxxxxxxxxxx',

  majorVersion: 1,
  minNodeVersion: '14.17.0',
  sampleCode: false,
  // deps: [],                /* Runtime dependencies of this module. */
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // devDeps: [],             /* Build dependencies for this module. */
  // packageName: undefined,  /* The "name" in package.json. */
});
project.gitignore.exclude('.env', '.idea');
project.gitignore.exclude('example/*.js', 'example/*.d.ts');
project.synth();
```

I am using projen version ^0.67.40

**Comment by mrgrain** [comment]
Thanks @alimhabib 
See https://github.com/projen/projen/labels/windows

Windows support unfortunately is very basic at the moment.

**Comment by RichiCoder1** [comment]
@mrgrain would ya'll take PRs to either de-shellify the code, or at least shim them via [@yarnpkg/shell](https://www.npmjs.com/package/@yarnpkg/shell)?

**Comment by mrgrain** [comment]
What exactly do you mean by "de-shellify"?

In terms of using a package, I'd prefer something smaller with less dependencies. Running basic shell scripts in Linux and Windows shouldn't be that complicated.

---

Either way I think the starting point would be adding a Windows test.

**Comment by RichiCoder1** [comment]
I recognize wanting to minimize dependencies, but there are assumptions being made with these shell commands that aren't easily solvable.

For example, for the package command it's running:
```shell
if [ ! -z ${CI} ]; then rsync -a . .repo --exclude .git --exclude node_modules && rm -rf dist && mv .repo dist; else npx projen package-all; fi
```

There's no simple way to make that cross platform without de-shellify since it (a) depends on bash specific conditionals and (b) references a non-default tool `resync`.

Even if you provided `cmd` and `pwsh` versions of the above script, you'd still run into the same issue.

Def open to contribute testing, but a decision will likely have to be made on a path forward.

**Comment by RichiCoder1** [comment]
For sure! Simplifying the command would go a long way too.

---

That's fair. I'm personal an advocate for avoiding shell at all cost because there's always quicks with doing so. I'd much rather advocate for a JS-based task runtime instead of Windows as you're still going to end doing redundant work to support multiple platforms vs just using natively cross-platform JS.

That said, I'd be willing to contribute a windows test suite to start!

**Comment by RichiCoder1** [comment]
It may also be worth adding some like this to a prominent portion of the readme so my fellow Windows-ies don't get suprised by this:

> **Warning**
> As of writing, many of the Projen Project constructs are only written with Linux and MacOS in mind (bash,zsh).
> Using `projen` with Windows is not supported, see https://github.com/projen/projen/issues/2427 for more details

**Comment by mrgrain** [comment]
> It may also be worth adding some like this to a prominent portion of the readme so my fellow Windows-ies don't get suprised by this:

I'd be open with a warning like this. Might need to spruce up the linked issue a bit 😅

**Comment by mrgrain** [comment]
> That's fair. I'm personal an advocate for avoiding shell at all cost because there's always quicks with doing so. I'd much rather advocate for a JS-based task runtime instead of Windows as you're still going to end doing redundant work to support multiple platforms via shell vs just using natively cross-platform JS.

The challenge is that moving features into JS is somewhat competing with the other goal of being runtime independent. I can see both being worthwhile; more native JS tasks is just the thing I haven't thought about yet very much.


> That said, I'd be willing to contribute a windows test suite to start!

Go for it! I reckon it would be a matter of running the existing test suite on a Windows runner while making sure it's not blocking builds.

Do we have a list yet if problematic commands? If not I hope the tests would give a good starting point.

**Comment by RichiCoder1** [comment]
> I'd be open to a warning like this. Might need to spruce up the linked issue a bit 😅

Ha, fair enough 😁

> The challenge is that moving features into JS is somewhat competing with the other goal of being runtime independent. I can see both being worthwhile; more native JS tasks is just the thing I haven't thought about yet very much.

That's fair. Unless the plan is to de-JS projen entirely (rust-based projen :D?), I'd say that anything that ultimately is behind `projen` facade can (and should?) be JS. Outside of that, I can see wanting to avoid a specific dependency.

**Comment by mrgrain** [comment]
I guess most commands currently in projen are effectively fancy redirects to other commands. I don't see that changing. Together with simple file operations provided by `shx` that should get as quite far.

The rest will be features using builtin commands that are written in JS (like `bump`). Those probably should be de-shellified where it makes sense.

**Comment by RichiCoder1** [comment]
I don't think I'll be able to contribute a test suite directly to this repository since the repository itself requires `bash` to bootstrap. However, I could take a different approach and have a "conformance suite" style e2e test in a separate repo that tries to exercise various commands and constructs on Windows to serve as an example.

**Comment by mrgrain** [comment]
That's also a good idea!
