### ISSUE TITLE
Running `npx projen` default task fails in subproject.

### ISSUE THREAD

**Issue by fynnfluegge** [projen/projen#2497]
The following wrong behaviour was discovered during implementation of #2418

**Current behaviour**:
Running `npx projen default` in the directory of a subproject fails with
```javascript
Error: Cannot find module 'path/to/projen-project/some/subproject/.projenrc.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Expected behaviour**:
Running `npx projen default` in the directory of a subproject should execute default task of the parent project.

&nbsp;
- [x] I may be able to implement this bug fix.

**Comment by mrgrain** [comment]
Code dump from an experiment. This goes into project.ts
But need a way to stop projects defining the task when it's a subproject

```ts
      if (this.parent) {
        this.defaultTask.exec(
          `cd ${path.relative(this.outdir, this.parent.outdir)} && ${
            this.projenCommand
          } ${Project.DEFAULT_TASK}`
        );
        this.defaultTask.lock();
      }

      // Only the top-level project can be ejected
      if (!this.parent) {
        this.ejectTask = this.tasks.addTask("eject", {
          description: "Remove projen from the project",
          env: {
            PROJEN_EJECTING: "true",
          },
        });
        this.ejectTask.spawn(this.defaultTask);
      }
```

**Comment by fynnfluegge** [comment]
Looks promising 👍 So let's just prevent subprojects from creating default task in their `tasks.json`, right?

**Comment by mrgrain** [comment]
Pretty much. I can see two general approaches:
- manually: wrap all the `this.defaultTask.exec()`'s in an if statement
  - Easy to implement
  - Flexible
  - Can be abstracted into a helper method
- forced: use the code snippet to reset the default task for subprojects just before synth
  - guaranteed to work
  - less code change
  - I think will take away option for project to do something differently

**Comment by fynnfluegge** [comment]
Guess I prefer the second approach, what do you think? Do you raise PR or should I?

**Comment by mrgrain** [comment]
> You mean if the default task was overridden? hmm..

Yes. Something like this might not be possible anymore: https://github.com/aws/aws-prototyping-sdk/blob/56cb484e29d074f82e65e3d9a647bdaeba28c33f/packages/nx-monorepo/src/nx-monorepo.ts#L510

This is a bit of a rabbit hole. I think I've tracked it down now though. The root cause appears to be that `Projenrc` components are added to a project disregarding of it is a subproject or not. Which kind of make sense, since so far mostly `Project` has concerned itself with that question (few exceptions apply). We should definitely tackle that and it will solve our question, since the default task is added via `Projenrc` 😅 

Not very helpful, I know. But we are getting there.
