### ISSUE TITLE
Confusing `npm install` behavior

### ISSUE THREAD

**Issue by mvs5465** [projen/projen#2554]
Hi, I am confused about how `npx projen`, `npx projen build`, and `npm install` work.

It looks like if I set a dependency in `.projenrc.ts` and then run `npx projen` then it will update package.json and package-lock.json to include this new dependency. However it does not appear to update the dependency in `node_modules/`. This often results in deploying old code being deployed.

Can someone explain if this behavior is intended, and how to fix it if so?

**Comment by mrgrain** [comment]
projen doesn't touch `package-lock.json`. What it does is updating `package.json` and if a change is detected it transparently calls the `install` command of your chosen package manger. Please look for the output the see what command it is running.

Since this is such a basic feature and literally runs without issue in very many projects, can you check your package manager configuration if it is correct and verify if your expected behavior is actually what is supposed to happen. For example a change in `package.json` or even `package-lock.json` doesn't guarantee an update to `node_modules`.

**Comment by mvs5465** [comment]
@mrgrain Is it possible that the `npm install` gets called in a subshell perhaps with different config?

This has been happening to my team and I for weeks, `npx projen` will update the `package.json` and `package-lock.json` files but the `node_modules/` directory is unchanged.

**Comment by mrgrain** [comment]
Yes that sounds about right. Most commands in projen are run via [spawnSync](https://nodejs.org/docs/latest-v18.x/api/child_process.html#child_processspawnsynccommand-args-options) in a sub-shel with the environment variables from the current process.

> This has been happening to my team and I for weeks, npx projen will update the package.json and package-lock.json files but the node_modules/ directory is unchanged.

Do you think this is changed behavior? Can you can confirm if an older version works differently?
What comes to mind is the change in #2494 which does change the `npm install` behavior from `execSync` to `spawnSync`. Although I don't think that should make any difference 🤔

**Comment by mvs5465** [comment]
Thanks - we are using `nvm` and I think it is causing a strange interaction here, seems like packages are being installed into a `$HOME/.nvm/node_modules` directory instead.

**Comment by mvs5465** [comment]
Yeah looks like this is an nvm issue. Sorry about that.

**Comment by mrgrain** [comment]
No need to be sorry! I love nvm but have run into problems with it myself many times.

I'm a bit surprised your env (seemingly) doesn't have the correct values to make it work.
