### ISSUE TITLE
Can't override tsconfig.compilerOptions without setting all defaults

### ISSUE THREAD

**Issue by benglass** [projen/projen#265]
This may be intentional, but it looks like the way the code is written, if you specify tsconfig.compilerOptions to the constructor of`ReactTypeScriptProject` it will never merge the provided options with the defaults. I believe the same is true of options.tsconfig.

https://github.com/projen/projen/blob/0efba69b33f937572f625d6e7295b5c5705ab8cc/src/react.ts#L76...L104

![image](https://user-images.githubusercontent.com/1964631/97822978-8dca3700-1c85-11eb-8fad-f6e8d1aa8d65.png)

The behavior im observing is consistent with this hypothesis (its not possible to override just one compilerOptions or tsconfig setting).

It would be nice to be able to provide some overrides without having to provide all of the values. On the other hand, if the user wants to provide a tsconfig explicitly and doesn't want to merge with the defaults that is also potentially a reasonable use case.

**Comment by Chriscbr** [comment]
This looks like a bug to me - there was a similar issue raised a while back (see #221). I believe the expected behavior is that options specified in the constructor props should merge with the default options that are already there - or at least I I'm guessing that's what most people expect based on the fact that two issues have been posted about it. 🙂 

As a temporary workaround for overriding individual options you can write:
```js
project.tsconfig.compilerOptions.noUnusedLocals = false;
```

To provide a tsconfig explicitly you can ignore the `tsconfig` prop in the constructor, and add the following:
```js
project.tsconfig = new TypescriptConfig(project, {
  include: ['src/**/*.ts'],
  exclude: ['node_modules', 'lib'],
  compilerOptions: {
    noImplicitAny: false
  }
})
```

I think there also ought to be a way to override the `compilerOptions` object while leaving other fields (`include`, `exclude`) intact - but I don't think there's currently a way to do so. I think we would need to add APIs in the TypescriptConfig class to enable this.

**Comment by pgollucci** [comment]
I agree @Chriscbr. This should might be a "good-first-ssue"
