### ISSUE TITLE
Prevent projects from defining mandatory options without a @default notations

### ISSUE THREAD

**Issue by eladb** [projen/projen#268]
Mandatory project options must be defined in `.projenrc.js`. This means that when users run `projen new TYPE`, the CLI needs to somehow assign values to these options. To hint to the CLI how to render these values, we use the `@default` docstring annotation, and also implement a bunch of "[macros]" that allow the CLI to assign a dynamic value.

If a project type has a mandatory option without a `@default` annotation, `projen new` will require that users assign a value using a command line switch (e.g. `projen new TYPE --my-option=value`).

From an ergonomics perspective, we try to make projen very convenient to use and get started with. Therefore, as a rule of thumb we want to enforce that mandatory options always denote their @default value (or macro), so that it's always possible to just run `projen new TYPE` and succeed.

Let's add a unit test (in inventory) that ensures that this is the case.

In the future, if we indeed have a case for mandatory options without a default assigned value, we can add some provisions to opt-out of this check.

[macros]: https://github.com/projen/projen/blob/a654767a7379309744dd73b48d7fd2f5b5bff67e/src/cli/cmds/new.ts#L116

**Comment by pgollucci** [comment]
👍

**Comment by Chriscbr** [comment]
This could be useful, but for now if a regression like this were to occur (where a mandatory field is added that doesn't have an `@default` annotation), then [new.test.ts](https://github.com/projen/projen/blob/master/test/new.test.ts) will fail (since it currently tries synthesizing every project type via the CLI without any extra options). So I think this issue is low priority.

**Comment by eladb** [comment]
Closing for now. @Chriscbr is correct that we actually enforce this via the "new" tests
