### ISSUE TITLE
Poetry `install` task updates project dependencies

### ISSUE THREAD

**Issue by myles2007** [projen/projen#2913]
# Overview
With the introduction of support for Python projects (https://github.com/projen/projen/pull/514) the `install` task for `Poetry` was defined as:

 - `poetry update` (https://github.com/projen/projen/blame/1020d0ad3f95bb4e1201f8640d440ffb43ccf230/src/python/poetry.ts#L30-34)

This is still the case today: https://github.com/projen/projen/blob/5c7f4202f47ff530f600edf1b8aec5e49e2ad3da/src/python/poetry.ts#L32-L34

The description does mention that this task also upgrades dependencies and it does work, but it also means tasks I expect to use my locked dependencies actually update my dependencies and rewrite `poetry.lock` which was unexpected. For example, running `projen build` or simply `projen` to update my project files also has the side effect of updating my Python dependencies.

Especially for fast changing libraries (e.g., `botocore`, `botocore_stubs`) this frequently results in updates which we may not want to take yet (or would like to take in the PRs generated by the `update` workflow). Our workflow may be partially at fault here, but it's also regularly causing failed builds for us due to mutations in files a developer isn't expecting to need to update. The `self-mutation` process does help out here to at least try to patch things up, but it's still not ideal in my view.

I'm not sure if there was specific reasoning behind this decision or not. If so and you believe it should persist, I'll be satisfied with some explanation and assistance. If the reasoning is unknown and/or you agree with me, I'd be happy to help resolve the issue.

Based on an error I recently encountered, I think there is a possibility this was done to prevent a message like the following which occurs if new dependencies are added to `.projenrc` and `poetry install` alone is used:
<img width="1153" alt="image" src="https://github.com/projen/projen/assets/235987/85f76553-d328-4824-a53d-025634ef198c">

# Potential Solution
We could redefine the `install` task for `poetry` to be: `poetry lock --no-update && poetry install`.

As I understand it, this will refresh the lockfile _without_ updating dependencies which resolved the error shared in my screenshot above and, I believe, should be safe for the general install workflow.

The `--no-update` functionality was added to `poetry` in October 2020, so it's been around for a while at this point:
<img width="605" alt="image" src="https://github.com/projen/projen/assets/235987/89a8dce2-ef26-434e-b31d-3916c1c6e2b8">

 - https://github.com/python-poetry/poetry/blob/master/CHANGELOG.md#111---2020-10-05
 - https://github.com/python-poetry/poetry/releases/tag/1.1.1

That said, it was pretty new at the time of the original code here and very possibly didn't exist during the original development of these features.

Given the longstanding nature of this behavior, I could see the need to introduce this behavior conditionally, but will definitely leave such decisions to the maintainers. :)

## Thanks
Thanks to everyone involved with `projen` for the hard work on this project!

**Comment by myles2007** [comment]
I've also just realized there is no distinct `update` task for Python so if `install` no longer runs `update` I think it would also be necessary to add a dedicate `update` task.

**Comment by myles2007** [comment]
In case it it's helpful to anyone who finds this issue, I have worked around this behavior for now by adding the following to my `.projenrc.ts` file:

```ts
myProject.removeTask("install");
myProject.addTask("install", {
  description: "Install dependencies",
  steps: [
    {
      exec: "poetry lock --no-update && poetry install",
    },
  ],
});
```

**Comment by mrgrain** [comment]
Thanks for reporting and for providing the workaround.

I think the idea was for `PythonProject` to behave the same as `NodeProject`.
The latter behaves differently when run locally or on CI. Locally, node "installs" the latest available version matching the version constraints and updates the lockfile. On CI, it strictly installs versions from the lockfile.

I'm not exactly sure how `poetry update` plays into this.
But I think the poetry equivalents of the above behavior would be:

```console
# local
poetry lock && poetry install

# CI
poetry lock --no-update && poetry install
```

Is that correct?

**Comment by scrthq** [comment]
@mrgrain `poetry lock` would be your lockfile updater command with Poetry, while `poetry update` is closer to `projen upgrade` in that it looks for the latest compatible versions across your dependency chain and updates your `poetry.lock` file and `pyproject.toml` accordingly. This is also within your version constraints, but if you are defining those semi-loosely (e.g. using [tilde requirements](https://python-poetry.org/docs/dependency-specification/#tilde-requirements) or [wildcard requirements](https://python-poetry.org/docs/dependency-specification/#wildcard-requirements), or really anything not locking to an explicit version), you run the risk of unexpected updates.

`poetry install` will install any missing package versions not found in your current environment that meet your constraints, meaning you could have a slightly older package with semi-loose constraints that will _not_ incur a change purely by running `poetry install` in that system. Again, mainly a symptom of loose version constraints IMO.


FWIW, an explicit `poetry lock` is typically only needed if you've updated the dependencies on the `pyprojecy.toml`. The provided command will cover things when updating dependencies via `.projenrc.py` since it's effectively managing the text content of the `pyproject.toml` file, not calling `poetry` to manage the content itself. I would personally _not_ want to run a `poetry lock` _and_ a `poetry install` on every `projen` call in some of my current environments where I'm using Poetry due to resolution latency in those environments, but I'm of the opinion that the default task should not be performing installs and that should be handled explicitly through `projen install`, as most of the time I'm running the default task locally and my dependencies are installed already. 

Maybe including some sort of marker in a `gitignored`'d file that is created during a `projen install` call which captures dependencies defined in the `.projenrc.X` configuration and conditionally runs the respective full commands if there are deltas between the marker file and what is currently defined.

**Comment by mrgrain** [comment]
I'm really not that familiar with the `PythonProject`, but the `NodeProject` only runs the install command when dependencies are changing (or actually the `package.json` file has changed). So this applies exactly what you're suggesting. To me, that behavior makes a lot of sense.

**Comment by JeremyJonas** [comment]
Definitely agree with @myles2007 in terms of current PythonProject `install` behavior is unexpected, as it continually performs operations expected in the `upgrade-deps` task. Node install does not update lock file unless there is a change in package.json or a discrepancy, such as version in node_modules does not match the lock (or node_modules does not exist).

The currently implementation constantly causes mutations in build (local and CI), I have had to write hacks to ignore poetry.lock files from git mutation checks. And for a large project, nearly every commit in my repo contains random poetry.lock updates. It is out of control. 

This looks like correct behavior to me as well
```
// local
poetry lock && poetry install

// CI
poetry lock --no-update && poetry install
```

and then should also update the `upgrade-deps` to call `poetry update` for PythonProject.

**Comment by garysassano** [comment]
### `NodeProject` + npm

- `install`: `npm install`
- `install:ci`: `npm ci`

### `NodeProject` + pnpm

- `install`: `pnpm i --no-frozen-lockfile`
- `install:ci`: `pnpm i --frozen-lockfile`

### `NodeProject` + yarn

- `install`: `yarn install --check-files`
- `install:ci`: `yarn install --check-files --frozen-lockfile`

To follow the same logic as the `NodeProject`'s package managers, I think:

### `PythonProject` + poetry

- `install`: `poetry update` (this is equivalent to `poetry lock && poetry install`)
- `install:ci`: `poetry install`

Note: The `install` command in poetry is nothing alike the other package managers. The big difference is that `poetry install` behaviour depends from the fact that `poetry.lock` already exists or not. If the lockfile already exists, it will honor it (thus behaving like a `--frozen-lockfile`); If it doesn't, it will install the latest version of the dependencies while also creating the lockfile.

For installations inside a CI system, you should always use `poetry install`, and `poetry.lock` should already be present in your repository. That's the case at least if you tested your app locally before publishing it to a remote repository. If you wanted to make sure that `poetry.lock` always exists (unnecessarily cautious), you could use `poetry lock --no-update && poetry install`.

**Comment by mrgrain** [comment]
> To follow the same logic as the `NodeProject`'s package managers:
> 
> ### `PythonProject` + poetry
> * `install`: `poetry update` (equivalent to `poetry lock && poetry install`)
> * `install:ci`: `poetry install` (equivalent to `poetry lock --no-update && poetry install`)

I'm slightly confused because it seems like https://github.com/projen/projen/pull/3321 has introduced exactly what you have noted as equivalent commands.

Other package managers guarantee the existence of a lockfile, thus we need to run `poetry lock --no-update` before `poetry install`.

**Comment by cogwirrel** [comment]
Cool that makes sense! Perhaps we delete the upgrade task if that’s equivalent to `poetry lock && poetry install`? I was imagining `poetry update` being a bit more like `npm-check-updates` but it seems it’s not!

I’m happy with `poetry update` instead of `poetry lock && poetry install` for the regular install task. The main thing I wanted out of the PR I raised was having a task which would install and honour the lockfile - so as long as `install:ci` is `poetry lock —no-update && poetry install` I’m happy :)

**Comment by garysassano** [comment]
To recap the functions of the tasks in `NodeProject`:

- `installTask`: Updates dependencies to their most recent compatible versions while ignoring the lockfile.
- `installCiTask`: Tailored for CI systems, it mandates the existence of a lockfile to proceed, immediately stopping if one is not found. When a lockfile is available, it proceeds to install the dependencies specified within, overlooking any available newer versions.

After consulting with Poetry's core team, for `PythonProject` using Poetry, the equivalents are outlined as follows:

- `installTask`: `poetry update`
- `installCiTask`: `poetry check --lock && poetry install`

Moreover, the `upgradeTask` for `PythonProject` using Poetry is redundant and can thus be removed.

**Comment by mrgrain** [comment]
What is the difference between `poetry check --lock` and `poetry lock --no-update`?

**Comment by garysassano** [comment]
@mrgrain 

- `poetry check --lock` does two things:
1) Checks that `poetry.lock` exists
2) Checks that `poetry.lock` is consistent with what's defined in `pyproject.toml`

If one of the two checks fails, it returns an error similar to `npm ci` and `pnpm i --frozen-lockfile`.

- `poetry lock --no-update` refreshes the `poetry.lock` file or generates a new one if it's missing. When creating a new lockfile, this action mirrors the effect of `poetry update`, as it will select the latest compatible versions of dependencies for the newly created lockfile.

**Comment by automartin5000** [comment]
I'm glad to see there was follow up conversation here after #3321 went live. I had a suspicion, but had not yet had a chance to confirm, that the #3321 was actually updating the lock file instead of using the frozen one similar to `npm ci`
