### ISSUE TITLE
Bug: projen fails to synthesize when passing in string arguments to the cli

### ISSUE THREAD

**Issue by kcwinner** [projen/projen#305]
When passing in string parameters to the command line projen parses them but then outputs them as values instead of strings. This prevents overriding string based parameter defaults.

Example:
`npx projen new awscdk-app-ts --cdk-version "1.65.0" --cdk-version-pinning true`
Same result with `"'1.6.0'"` and `'"1.65.0"'`

Outputs the following `.projenrc.js`:
```javascript
const { AwsCdkTypeScriptApp } = require('projen');

const project = new AwsCdkTypeScriptApp({
  cdkVersion: 1.65.0,
  cdkVersionPinning: true,
  name: "projen-testing",
})
```

**Comment by eladb** [comment]
Definitely a 🐛

**Comment by kcwinner** [comment]
If we pass in our own value for a string param `yargs` parses as:
```
{
  _: [ 'new', 'awscdk-app-ts' ],
  'cdk-version': '1.65.0',
  cdkVersion: '1.65.0',
  'cdk-version-pinning': true,
  cdkVersionPinning: true,
  synth: true,
  comments: true,
  ...
  name: '"projen-testing"',
  ...
}
```

However, since all string default values have `""` around them and get injected with values by the builder, we can't simply `JSON.stringify()` by the time we get to renderParams
```
{
  cdkVersion: '1.65.0',
  name: '"projen-testing"',
  cdkVersionPinning: true,
  ...
}
```

Figured it's worth discussing in here as this portion of the application is pretty important.

**Comment by gradybarrett** [comment]
@kcwinner, this might be ill-informed, but it seems like we should be stripping quotes during discovery. I would think the extra characters is something we'd want to leave behind at the boundary of projen, so that they don't negatively impact the rendering of values.

Put another way, just because a value is declared in the jsii manifest with certain characters, doesn't mean that projen needs to preserve that representation. In this case, those characters are actually undesirable for projen's purposes.

**Comment by eladb** [comment]
Working on it.
