### ISSUE TITLE
"release" failed when executing "git diff --ignore-space-at-eol --exit-code"

### ISSUE THREAD

**Issue by ankitatdnv** [projen/projen#3171]
Hi,

I am using projen for CDKTF project in typescript, and I am generating a .sh using .projenrc.ts file. But while releasing it's failing while executing "git diff --ignore-space-at-eol --exit-code" with following message:
```
diff --git a/scripts/terraform-docs.sh b/scripts/terraform-docs.sh
old mode 100644
new mode 100755
```

I am working in Windows OS, whereas release workflow is running on ubuntu.
Also when I removed terraform-docs.sh file generation from projenrc.ts then release was working fine, so problem is with mode of the generated file from Windows OS and Ubuntu.

Can you please provide some pointer, to resolve this issue.

**Comment by mrgrain** [comment]
I suspect that on windows the file ends up being added to git with `mode 100644` - maybe because the permissions get messed up? But that's how it ends up being checked in and pushed.

Then during release the integration checks runs `projen` again, but this time on windows and the file get's a different mode `100755` and the release workflow will then stop due to safety concerns.

You might try doing the following on windows and committing the change:

```
git update-index --chmod=+x scripts/terraform-docs.sh
```
