### ISSUE TITLE
NpmConfig uses package 'ini' which adds CRLF on Windows

### ISSUE THREAD

**Issue by pavlovecjakePFG** [projen/projen#3545]
I ran into an issue where developers on Windows generated a different .npmrc file with the NpmConfig class then developers on Ubuntu. The cause is the use of the 'ini' package for the .npmrc file: 
https://github.com/projen/projen/blob/6ee24aaded54c9ceaaae8ee5c7472e17c89b87cb/src/javascript/npm-config.ts#L38. 
That package adds CRLF on Windows, but just LF on Ubuntu. 

This results in the mutation check constantly failing as different developers commit slightly different versions of the .npmrc file. 

I believe this file could just as easily be created with TextFile, which would avoid this problem.

**Comment by mrgrain** [comment]
We can upgrade to the latest version of the ini library and hardcode the platform option to unix.

https://www.npmjs.com/package/ini?activeTab=readme

**Comment by gmeligio** [comment]
Hardcoding the platform in `INI.stringify` would work.

But this could happen to multiple file formats managed by multiple packages and tools. A more general solution could be to hardcode the Linux line ending when `.gitattributes` is generated, moving the responsibility to git instead of the particular package. I faced a similar problem when doing changes in projen itself, and `gitattributes` worked well in:

https://github.com/projen/projen/blob/f34f8a020c6a7cb41688b867c69abcb95b921924/projenrc/index.ts#L346

What do you think of using gitattributes?

**Comment by mrgrain** [comment]
Yep I didn't know gitattributes can do that until you did it! 

It's probably a more generic and therefore better solution. I guess we can make it a setting and default to using Unix linebreaks.
