### ISSUE TITLE
Export util modules

### ISSUE THREAD

**Issue by langri-sha** [projen/projen#3548]
The [`util` modules](https://github.com/projen/projen/tree/main/src/util) contain a lot of genuinely useful helpers that those of us building custom Projen components would want to use in our projects. Indeed, here's a [quick search](https://github.com/search?q=projen%2Flib%2Futil&type=code) to show that there are active projects out there that use helpers such as [`deepMerge`](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util.ts#L236).

I am trying to use an ESM loader for my Projen configuration, and I'm getting an [`ERR_UNSUPPORTED_DIR_IMPORT`](https://nodejs.org/api/errors.html#err_unsupported_dir_import). We're forced to do directory imports, because these haven't been exported from the main module.

Resolving this issue would bring us close to ESM support mentioned in #2977.

**Comment by langri-sha** [comment]
I'll leave this as a workaround when authoring your own changes:

```
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const { deepMerge } = require('projen/lib/util')
```

**Comment by mrgrain** [comment]
We're not keen on this because it creates a lot of maintenance surface the is completely unrelated to the core of the project.

E.g. why can't you use [lodash.merge](https://www.npmjs.com/package/lodash.merge)?

The reason people are using these, is because projen currently doesn't actively prevent the imports by not setting an experts field. But we will eventually and I think many people are aware that path imports are bad practice.

**Comment by langri-sha** [comment]
@mrgrain that makes sense. 

I have to think how I wouldn't have started publishing anything that's built on top of Projen if I couldn't have leveraged things like `xSnapshot` in my packages for writing tests on day 1, though. And, I think it natural for @cdklabs and others to repeat the same patterns and use the same abstractions from Projen. 

I wonder if you would reconsider making a plan of publishing these separately, eventually. It's not that these things can't be reverse engineered and alternatives provided, but it doesn't make a great foundation for building on top of Projen if this also has to be in the list of things that need to be solved before commencing actual work.

**Comment by mrgrain** [comment]
This is a good point. But I think we should be talking about which parts of `utils` we want to include explicitly vs. the parts that are easily available outside of projen (like `deepMerge`). I definitely see the need for projen testing helpers being readily available.

Maybe if you could start with a more focused proposal on what exactly of the current `utils` we should export?

**Comment by langri-sha** [comment]
I've only started building on top of a small part of what's exposed, and things that I found incredibly useful right away, but aren't made available by other means are [`synthSnapshot`](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util/synth.ts#L31), and [`directorySnapshot`](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util/synth.ts#L107).

Things that seem to become important quite quickly are [`exec`](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util.ts#L21C17-L21C21), [`writeFile`](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util.ts#L106). There's other things surfacing from the [GitHub-wide search](https://github.com/search?q=projen%2Flib%2Futil&type=code), for packages that will break with ESM changes. 

I guess these aren't really something that's essential, but they are imbued with certain particularities, and it does save others from re-implementing these, and in a way that's not consistent with how projen behaves.

**Comment by mrgrain** [comment]
>I've only started building on top of a small part of what's exposed, and things that I found incredibly useful right away, but aren't made available by other means are [synthSnapshot](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util/synth.ts#L31), and [directorySnapshot](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util/synth.ts#L107).

Yep, that's the beginning of a testing library.

> Things that seem to become important quite quickly are [exec](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util.ts#L21C17-L21C21), [writeFile](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util.ts#L106). There's other things surfacing from the [GitHub-wide search](https://github.com/search?q=projen%2Flib%2Futil&type=code), for packages that will break with ESM changes.

The issue I have with those is what are they even used for? These are low level helpers used by the proper features like File constructs and tasks. Why are the high-level features not used?

**Comment by langri-sha** [comment]
@mrgrain I found that since Projen provides no way to hook into modifying the contents of files as they are written by components outside one's control, nor there being support for replacing contents of `FileBase` instances one has a reference to, we all simply have to share process and disk space, from the way I understand things.

If providing these is contentious, then it's hinting that something could use some thinking through from the grounds up, perhaps by providing these hooks, and offering us to interject asynchronously as well, if we need to. Then there wouldn't be need to reach for helpers to mutate the disk, or running child processes for ad-hoc tasks, but as things stand now these might be needed for anything beyond the basics from what I can tell.

**Comment by mrgrain** [comment]
Thanks for your response @langri-sha ! I don't want to put this all on you, just because you are the person who brought it up. And I very much appreciate you for starting this discussion. So whenever I mention users, please know that I'm really not just talking about you!

> @mrgrain I found that since Projen provides no way to hook into modifying the contents of files as they are written by components outside one's control,

Yes, this is the main problem with OOP and even worse with the Constructs Programming Model that really wants to have correctness at construction time. The AWS CDK suffers from the same problem.

> nor there being support for replacing contents of `FileBase` instances one has a reference to, we all simply have to share process and disk space, from the way I understand things.

In projen everything ends up being something that's written to the disk. That's why we already have the [low level object file APIs](https://projen.io/docs/concepts/escape-hatches). I'm are we are missing one for plain text files. Tasks have their own extension API, but can also be changed using files. Other than that - what use cases are still missing here?

> If providing these is contentious, then it's hinting that something could use some thinking through from the grounds up, perhaps by providing these hooks, [...].
> Then there wouldn't be need to reach for helpers to mutate the disk, or running child processes for ad-hoc tasks, but as things stand now these might be needed for anything beyond the basics from what I can tell.

Yes absolutely spot on. We technically already have pre and post synth hooks, but they are not very extensible at the moment. What I'm missing from this discussion is some _concrete_ examples of things users cannot do right now, and thus pushes them to use these helpers.

One thing that I came across for `deepMerge` is merging options with defaults. I was hoping to provide an explicit feature for this in projen.

Do you know of anything else?

> and offering us to interject asynchronously as well, if we need to.

Async is unfortunately a completely different discussion. It's just not possible in a constructor (which doesn't matter for hooks) and not (well) supported in jsii, which itself is a non-negotiable core tenet of projen.

**Comment by cameroncf** [comment]
> I've only started building on top of a small part of what's exposed, and things that I found incredibly useful right away, but aren't made available by other means are [`synthSnapshot`](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util/synth.ts#L31), and [`directorySnapshot`](https://github.com/projen/projen/blob/5b569719adea139555345755925e40d9a6e33fd8/src/util/synth.ts#L107).

Agree. Synth for files and directories (without writing to disk) comprise the bulk of my local test utils for Projen related things. They are mostly cut/paste from Projen but it would be nicer to just import from Projen directly. Being able to snapshot a synth'd file output is a great cheap way to know what's changed during synth without jumping through hoops.
