### ISSUE TITLE
New external projects lead to invalid .projenrc.js file

### ISSUE THREAD

**Issue by pgarbe** [projen/projen#384]
When I create a new project from an external npm package, the generated .projenrc.js file does not contain quotes for string values, e.g. cdkVersion and fails

```
/foo/.projenrc.js:4
  cdkVersion: 1.73.0,
                  ^^

SyntaxError: Unexpected number
```

The file looks like this:
```
const project = new TaimosCdkApp({
  cdkVersion: 1.73.0,
  devDeps: ["@taimos/projen"],
  name: foo,
```

How to reproduce:

```
# Optional run in container: docker run -it node:14 /bin/sh
npx projen new --from @taimos/projen taimos-cdk-app --synth false
cat .projenrc.js
```

**Comment by kcwinner** [comment]
I've narrowed it down to the cli changes from `0.5.2` to allow passed in string values to parse properly.

The differences come from the fact that the regular `projen new` passes in cli options from the command generator whereas the `projen new --from` does now have these available due to needing to discover (at least as far as I can tell)
