### ISSUE TITLE
Release tags pushed without bump commit

### ISSUE THREAD

**Issue by hoegertn** [projen/projen#553]
If you have mergify and dependabot activated it leads to multiple merges and multiple release builds. They conflict when pushing the release which leads to tags being pushed but not released and any subsequent run then fails as the tag already exists.

https://github.com/taimos/taimos-projen/runs/1908575787?check_suite_focus=true

https://github.com/taimos/taimos-projen/runs/1925027653?check_suite_focus=true

I have this on nearly all of my projects, so no one-time issue.

Any idea or guidance on this?

**Comment by eladb** [comment]
Damn. Not nice. I am not sure I fully understand what's going on, but we should fix this ASAP.

**Comment by eladb** [comment]
Okay, this is basically a latent bug in our per-commit release model which is caused by multiple commits pushed to `main` at the same time (or close together). What happens is that the first commit triggers the "release" workflow, but when the workflow reaches the bump + push step, there are already new commits on "main". The tag push works but the bump commit push is rejected (because there are new commits), and now we basically have a tag without a bump.
