### ISSUE TITLE
Projen removes files that contain "// ~~ Generated by..." automatically

### ISSUE THREAD

**Issue by skyrpex** [projen/projen#609]
Since `0.16.42`, projen removes my files that contain the string `// ~~ Generated by...` in it. It thinks that those were generated by projen, but they weren't.

A possible solution would be to keep track of the generated files the same way `.projen/deps.json` does with the node dependencies, am I right?

**Comment by Chriscbr** [comment]
I'm not 100% sure, but I think this is an intended behavior. This will prevent issues where you might have a component like "Jest" that creates a config file (with the "Generated by..." tag), and if you later remove the component, the config file should get cleaned up automatically, instead of getting orphaned. If there are files that should only get created by projen once and not get automatically removed (e.g. `SampleFile`s) then those should probably not have the special tag on them.

My current mental model is really one where it should say "// ~~ Managed by projen" to emphasize this point, but it's possible the marker isn't intended to be used like that. (cc @eladb )

What was the scenario where you had files with the "Generated by" tag that you wanted to keep?

**Comment by skyrpex** [comment]
Sure sure, the feature is fine! I want projen to remove generated files if I'm not using the projen component that created those anymore, but I'm getting false positives with files of my own just because I have the `// ~~ Generated by...` string in them somewhere.

That's why I'm mentioning that maybe explicit tracking would be better rather than deducing if a file was generated by projen.

**Comment by Chriscbr** [comment]
Ah, got it. I can see how explicit tracking has some benefits. Perhaps there could be an API like `project.preserveFiles(...)`.

As a side note, in some cases you can just hack around this in source code files by writing "~~ Generated by " + "projen", as done [here](https://github.com/projen/projen/blob/main/src/common.ts). But it's still a valid issue to bring up. :-)

**Comment by eladb** [comment]
@skyrpex I am wondering if [`project.addExcludeFromCleanup()`](https://github.com/projen/projen/blob/d54f83639ead24368c8cef36736396b4e18b4856/src/project.ts#L344) is good enough for your use case?

**Comment by skyrpex** [comment]
> @skyrpex I am wondering if [`project.addExcludeFromCleanup()`](https://github.com/projen/projen/blob/d54f83639ead24368c8cef36736396b4e18b4856/src/project.ts#L344) is good enough for your use case?

Yes, that's good enough indeed 👍🏻
