### ISSUE TITLE
Disabling tailwind leaves orphaned postcss.config.json file

### ISSUE THREAD

**Issue by gillisandrew** [projen/projen#751]
In a nextjs project if you disable tailwind (i.e. `tailwind: false,` in your `.projenrc.js`) it properly removes the tailwind config file but leaves the postcss config file that must be manually deleted before next will build properly.

**Comment by Chriscbr** [comment]
Thanks for reporting this.

The cause is that projen usually includes a "Generated by projen...' comment in most files so it can identify if each file needs to be cleaned up, but we disabled the tag for this postcss file because it was causing a small warning in NextJS's build tools. For now you can delete it manually.

Maybe it's worth reverting #685? cc @pgollucci

**Comment by pgollucci** [comment]
This file really should be a .js which would make the above moot and it can come back.

**Comment by pgollucci** [comment]
https://github.com/projen/projen/pull/704

**Comment by gillisandrew** [comment]
Yeah JS should work too although interestingly nextjs seems to handle comments in the json file just fine (if you can ignore vscode's complaints).
