### ISSUE TITLE
Seems like updating compilerOptions/lib does not change tsconfig.json

### ISSUE THREAD

**Issue by markusl** [projen/projen#769]
Seems like updating compilerOptions/lib does not change tsconfig.json

Example commit:
https://github.com/markusl/cdk-codepipeline-bitbucket-build-result-reporter/commit/0c6d5c10e0938cde5b054f19a1e7e6b0427fb7b6

Seems to change tsconfig.eslint.json and tsconfig.jest.json but not tsconfig.json.

Any idea what to do to also update the value in tsconfig.json?

**Comment by Chriscbr** [comment]
Sorry for the confusion this must have caused. 😕 Right now jsii-based projects disable generating `tsconfig.json` through projen because it is gets generated by jsii. (You should see at the bottom of your tsconfig.json it says "Generated by jsii"). Because of this, any tsconfig we would generate would get overriden by jsii and cause the compiler to complain.

It looks like a potential feature to customize `tsconfig.json` further is being tracked here: https://github.com/aws/jsii/issues/2071

Hope this helps.

**Comment by markusl** [comment]
We'd still like to see this fixed to be able to properly customize the tsconfig file.

**Comment by markusl** [comment]
This issue is still relevant to us. Ping @RomainMuller @Chriscbr

**Comment by nickehunt-idm** [comment]
Bumping this to see if we can get this back going since having a similar issues with tsconfig.json and configuration changes...

**Comment by pbredenberg** [comment]
We're trying to migrate some older projects to Projen and this would be a nice feature to have as we modernize our stack.

**Comment by mrgrain** [comment]
This has nothing to do with projen. You are looking for this issue: https://github.com/aws/jsii/issues/2071
