### ISSUE TITLE
upgrade-dependencies workflow can’t trigger workflows for PR

### ISSUE THREAD

**Issue by zxkane** [projen/projen#915]
I noticed the PR created by auto workflow `upgrade-dependencies` not triggering other PR workflows.

Checked the PRs in `projen`, the behavior is same.

Check the `build` action triggered by `update-dep` workflow, the build was successful in **0 second** without any action output. It actually breaks the automation testing.

https://github.com/projen/projen/pull/911/checks?check_run_id=2957685959

Comparing to the build action triggered by a PR issued in a normal process,

https://github.com/projen/projen/pull/913/checks?check_run_id=2963517874

**Comment by zxkane** [comment]
@eladb what do you think?

**Comment by Chriscbr** [comment]
@zxkane The default `upgrade-dependencies` workflow manually overrides the automatic `build` check to have a "completed" status, so that is why it says the build was successful in 0 seconds.

The reason other workflows for PRs are not triggered is because GitHub has restrictions limiting how workflows can trigger other workflows when using GITHUB_TOKEN - see https://docs.github.com/en/actions/reference/events-that-trigger-workflows. For example, creating a pull request in a workflow will never start workflows with the "on: pull_request" trigger.

So I think if you want certain other workflows to run on the PR, you would need to define it to be triggered by the "workflow_run" event, or add it as an extra job to this upgrade-dependencies workflow.

**Comment by zxkane** [comment]
@Chriscbr thanks for your information. Hooking the event of `workflow_run` of `update deps` PR is a decoupled way, which sounds good. Do you know if it’s doable to update the check status of PR from a downstream workflow? is there any working example for reference?
