### ISSUE TITLE
CI/CD abstraction

### ISSUE THREAD

**Issue by joostvdwsd** [projen/projen#942]
Hi all,

i was wondering if there were already some attempts to make the pipeline/workflow generation more abstract.
Projen now generates github workflows. We also generate azure devops pipelines in our company packages and i’ve seen people talk about gitlab and travis ci.

In our packages i see a lot of similarities with the github flow and it should be easy to make this more plugin/interface based. 

This is probably a major change. I would not mind taking some of the burdon for this since in the end we would also be helped by a more standardized approach within our company (projen is becomming more and more a goto tool after we standardized  company project types with all security an dcompliancy rules in code) 

especially with the tasks of projen the workflows are getting very simple so a generic approach should be doable. As long as you have your escape hatches in place per implementation it should work

**Comment by eladb** [comment]
We haven't made an attempt yet, but definitely interested in this space. 

My general thinking (as you implied) is to enhance "tasks" so they will be able to model all the standard workflows and render into platform-specific workflows.

Since this is a pretty major change, I would prefer it if you took some time to write an RFC with your proposal. You can use the CDK team's [RFC template](https://github.com/aws/aws-cdk-rfcs/blob/master/0000-template.md) as a baseline and submit a PR with a document under a new directory called `rfcs/`.

**Comment by joostvdwsd** [comment]
Ok, gonna give it a try. Got some general idea on how to structure it. 

Btw, maybe a nice idea to "slowly" work towards it. for instance, in projen you have the release jobs where you have command lines for npm, maven and python packages. This kind of logic could already be nicely implemented as a projen task through:
release:npm
release:maven
release:pypi

as task this also has a nice remark. Would these tasks also build, would they run on the existing dist folder or would it build when there is no dist folder
