### ISSUE TITLE
GitHub workflow that adds release metadata to merged pull requests

### ISSUE THREAD

**Issue by Chriscbr** [projen/projen#953]
Wild idea, but curious if it has any merit.

## Scenario

You are trying to find out when a bug was fixed in a package, and whether the bug fix was integrated into a package's dependent or not. You search through GitHub issues/PRs, and find the original pull request merged a month ago that fixed the bug. Now you wonder, which release included this bug fix? To figure this out, you currently have to look through the GitHub releases or look at the git history tags to determine what version the commit was added in.

## Solution

A GitHub workflow step that automatically edits the appropriate pull request description(s) with a quick blurb like "**Note: The changes in this pull request were added in v1.2.3**". Included would be a link to the GitHub release or changelog entry.

## Questions

- Are there any other convenient solutions for this?
- How difficult is this to implement?
- Would this be better scoped as a GitHub action, or as a Projen integration...?

**Comment by mmcculloh-dms** [comment]
I have been thinking about this sort of thing as well, was probably going to implement it soon at my company. Some thoughts/questions:
- Would it be better for a comment to be added instead of modifying the description?
  - I feel like a comment would be more visible, but I suppose that's only if one scrolls down
- This seems a lot easier to implement if a specific flow is enforced (e.g. trunk based development + PRs are always squashed so that 1 commit in trunk = 1 PR to update)
- How to handle reverts, if at all.

To be honest this does seem to escape the scope of projen and would be something found in a separate projen-based lib. Then again, I don't really know where the power of projen is supposed to end.

**Comment by Chriscbr** [comment]
I like the idea of using a comment instead - definitely a bit less invasive (and still fairly visible). I would just skip the issue of reverts / plainly treat them like other commits.

> Then again, I don't really know where the power of projen is supposed to end.

Projen's power has no bounds! 🚀

**Comment by eladb** [comment]
Not wild at all. I've seen this done in other projects. I bet there's some GitHub action that does that.

Love it ❤️

Would it make sense to add a label in addition to a comment? So it will be possible to search by version? With release per commit this might be too much though.

Also, we should trace back issues that are addressed by the PRs and make sure to add a comment there as well.

BTW, the changelog generator actually does most of this work already. We could technically just scan the changelog for all references to issues and pull requests and add a comment to each one there. Should be trivial.

**Comment by Chriscbr** [comment]
I did some work to prototype this, but I ended up not productionizing it into a GitHub action for now since I didn't think it created enough value. As a substitute, I found that the [refined-github](https://github.com/sindresorhus/refined-github) Chrome extension has a feature that shows the first Git tag a merged PR was included in ([screenshot](https://user-images.githubusercontent.com/16872793/81943321-38ac4300-95c9-11ea-8543-0f4858174e1e.png)), which addresses the scenario from the original post.

Closing this for now but open to revisiting it in the future.
