### ISSUE TITLE
Representation of projenrc as json

### ISSUE THREAD

**Issue by alexforsyth** [projen/projen#990]
We would like to be able to declaratively talk about projen rcs.

**Comment by eladb** [comment]
@Chriscbr is this something you'd like to work on?

**Comment by Chriscbr** [comment]
Sure, I can take a look at some point. This could be a neat POC to build.

What are some use cases for this? I'm inclined to say this would be useful in one way or another, but concrete examples would be helpful to motivate the design.

For example: Would this be used to run a "diff" between projen configurations that people have already written in javascript/python/etc. (through some process of converting the files to JSON)? Or do we just want to support JSON as an additional input format that doesn't necessarily achieve feature parity with the other rc formats? (Since if you are using JSON, you can't model for loops, or functions, etc.)

@eladb @alexforsyth
