### ISSUE TITLE
Use @yarnpkg/shell for exec as a cross-platform shell

### ISSUE THREAD

**Issue by mmcculloh-dms** [projen/projen#997]
https://www.npmjs.com/package/@yarnpkg/shell
https://github.com/yarnpkg/berry/tree/master/packages/yarnpkg-shell

This should replace the need for `shx` and should *generally* make exec behavior consistent across platforms. And in the case of windows, it'll greatly improve it 😁

I suppose it could also be the case that one can opt-in to a native shell.

**Comment by MarkMcCulloh** [comment]
Did some experimentation with this:
- Due to their shell being async only, something like https://github.com/mentrena/SyncKit would be also be needed
- This probably won't be possible without https://github.com/aws/jsii/pull/2377 being merged and projen setting up a custom tsconfig for jsii. Some of .d.ts files in depedencies of `@yarnpkg-shell` conflict with the default tsconfig (esModuleInterop and the 'dom' lib are used)

**Comment by eladb** [comment]
Can you describe the difference between `shx` and the yarn shell package? Why doesn't `shx` fit the bill?

**Comment by MarkMcCulloh** [comment]
While shx gives us the portable built-ins, the yarn shell also portably gives us: (copied from repo)

- Supports glob patterns (only for files that exist on the filesystem: ls *.txt)
- Supports logical operators
- Supports subshells
- Supports variables
- Supports string manipulators
- Supports argc/argv
- Supports background jobs with color-coded output
- Supports the most classic builtins

With these in place, I think it make much easier to add additional features to the task system and make the OS parity sufficient for more people.
